// "use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
//import Navbar from "../components/nav";
import Navbar from "@/components/Navbar";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
        <div style={{ display: 'flex', flexDirection: 'column', minHeight: '100vh'}}>
            <Navbar/>
          <div style={{ flex: 1, display: 'flex', justifyContent: 'center', alignItems: 'center'}}>
            {children}
          </div>
        </div>
        
       
      
      </body>
      
    </html>
  );
}
